#ifndef _LINUX_SUSFS_DEF_H
#define _LINUX_SUSFS_DEF_H

/* 定义 SUSFS 相关的常量 */
#define SUSFS_MAX_LEN_PATHNAME 256

/* 定义 SUSFS 特性相关的配置选项 */
#define CONFIG_KSU_SUSFS_SUS_PATH 1
#define CONFIG_KSU_SUSFS_SUS_MOUNT 1
#define CONFIG_KSU_SUSFS_SUS_KSTAT 1
#define CONFIG_KSU_SUSFS_TRY_UMOUNT 1
#define CONFIG_KSU_SUSFS_SPOOF_UNAME 1
#define CONFIG_KSU_SUSFS_OPEN_REDIRECT 1
#define CONFIG_KSU_SUSFS_SUS_SU 1
#define CONFIG_KSU_SUSFS_ENABLE_LOG 1
#define CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG 1
#define CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT 1
#define CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT 1
#define CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT 1

#endif /* _LINUX_SUSFS_DEF_H */